version: "2"

volumes:
  db-data:
    external: false
  elasticsearch:
    driver: local

services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 15672:15672

  db:
    image: postgres
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/db-data

  app:
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
    links:
      - rabbitmq
            