
development:
  secret_key_base: 2bd829edb1e04d98dc8b1323bc7f4408cc5b6e7e8cd5ad6260b2f6bb5002d9dde2660c7d5e8c33367a04330b23ddbb0c524b789a658e0264b0a26b6be3e3e5ee
  database:
    master:
      adapter: "postgis"
      pool: "5"
      username: "postgres"
      password: ""
      host: postgres
      port: "5432"
      database: "db_bug_development"

test:
  secret_key_base: f061567dabc2aff80d7f625365b7c8ca45abbc172a641a7dfb6a41d616cef4102e86467c6c07c2dccdb64a79836e3ec3539918109f0b49c0dda150b7d613285b
  database:
    master:
      adapter: "postgis"
      pool: "5"
      username: "postgres"
      password: ""
      host: postgres
      port: "5432"
      database: "db_bug_test"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

